services:
  next:
    build: .
    container_name: v-svo-next
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_ORIGIN=https://v-svo.ru
    expose:
      - '3000'

  nginx:
    image: nginx:stable-alpine
    container_name: v-svo-nginx
    restart: always
    ports:
      - '3000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - next
