services:
  next:
    build: .
    container_name: v-svo-next
    restart: always
    environment:
      - NODE_ENV=production
      - SITE_ORIGIN=https://v-svo.ru
      - API_ORIGIN=http://host.docker.internal:3500
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    expose:
      - '3000'

  nginx:
    image: nginx:stable-alpine
    container_name: v-svo-nginx
    restart: always
    ports:
      - '3000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - next
